// <auto-generated />
using System;
using EFIntroPD422;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFIntroPD422.Migrations
{
    [DbContext(typeof(AirLinesDbContext))]
    [Migration("20250314132758_seedAllData")]
    partial class seedAllData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientFlight", b =>
                {
                    b.Property<int>("ClientsId")
                        .HasColumnType("int");

                    b.Property<int>("FlightsId")
                        .HasColumnType("int");

                    b.HasKey("ClientsId", "FlightsId");

                    b.HasIndex("FlightsId");

                    b.ToTable("ClientFlight");
                });

            modelBuilder.Entity("EFIntroPD422.Entities.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxPassengers")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airplanes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxPassengers = 140,
                            Model = "Boeng 747"
                        },
                        new
                        {
                            Id = 2,
                            MaxPassengers = 130,
                            Model = "Airbus A320"
                        },
                        new
                        {
                            Id = 3,
                            MaxPassengers = 120,
                            Model = "Boeng 737"
                        },
                        new
                        {
                            Id = 4,
                            MaxPassengers = 150,
                            Model = "Airbus A380"
                        });
                });

            modelBuilder.Entity("EFIntroPD422.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FirstName", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan@gmail.com",
                            Name = "Ivan"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1992, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petro@gmail.com",
                            Name = "Petro"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vasyl@gmail.com",
                            Name = "Vasyl"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(1998, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oleg@gmail.com",
                            Name = "Oleg"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(2000, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olena@gmail.com",
                            Name = "Olena"
                        });
                });

            modelBuilder.Entity("EFIntroPD422.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirplaneId = 1,
                            ArrivalCity = "Lviv",
                            ArrivalTime = new DateTime(2021, 10, 10, 12, 10, 10, 0, DateTimeKind.Unspecified),
                            DepartureCity = "Kyiv",
                            DepartureTime = new DateTime(2021, 10, 10, 10, 10, 10, 0, DateTimeKind.Unspecified),
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            AirplaneId = 2,
                            ArrivalCity = "Kyiv",
                            ArrivalTime = new DateTime(2021, 10, 11, 13, 11, 11, 0, DateTimeKind.Unspecified),
                            DepartureCity = "Lviv",
                            DepartureTime = new DateTime(2021, 10, 11, 11, 11, 11, 0, DateTimeKind.Unspecified),
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            AirplaneId = 3,
                            ArrivalCity = "Odesa",
                            ArrivalTime = new DateTime(2021, 10, 12, 14, 12, 12, 0, DateTimeKind.Unspecified),
                            DepartureCity = "Kyiv",
                            DepartureTime = new DateTime(2021, 10, 12, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 4,
                            AirplaneId = 4,
                            ArrivalCity = "Kyiv",
                            ArrivalTime = new DateTime(2021, 10, 13, 15, 13, 13, 0, DateTimeKind.Unspecified),
                            DepartureCity = "Odesa",
                            DepartureTime = new DateTime(2021, 10, 13, 13, 13, 13, 0, DateTimeKind.Unspecified),
                            Rating = 4.7000000000000002
                        });
                });

            modelBuilder.Entity("ClientFlight", b =>
                {
                    b.HasOne("EFIntroPD422.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFIntroPD422.Entities.Flight", null)
                        .WithMany()
                        .HasForeignKey("FlightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFIntroPD422.Entities.Flight", b =>
                {
                    b.HasOne("EFIntroPD422.Entities.Airplane", "Airplane")
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("EFIntroPD422.Entities.Airplane", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
